# This workflow will publish a package to GitHub Packages when a release is created.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish NPM package

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: "yarn"
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.token }}
